# Generated by Django 4.2.4 on 2023-08-07 18:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_account', models.CharField(max_length=64)),
                ('local_account', models.CharField(max_length=64)),
                ('delay', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeout', models.FloatField(default=60.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='config',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('remote_account', 'local_account'), django.db.models.functions.comparison.Greatest('remote_account', 'local_account'), name='unique_account_pair'),
        ),
    ]
